// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"time"
)

// Argument defines model for Argument.
type Argument struct {
	Id    *Uint64String `json:"id,omitempty"`
	Name  *string       `json:"name,omitempty"`
	Value *string       `json:"value,omitempty"`
}

// AssistantConversation defines model for AssistantConversation.
type AssistantConversation struct {
	Arguments                    *[]Argument                            `json:"arguments,omitempty"`
	AssistantConversationMessage *[]AssistantConversationMessage        `json:"assistantConversationMessage,omitempty"`
	AssistantId                  *Uint64String                          `json:"assistantId,omitempty"`
	AssistantProviderModelId     *Uint64String                          `json:"assistantProviderModelId,omitempty"`
	Contexts                     *[]AssistantConversationContext        `json:"contexts,omitempty"`
	CreatedBy                    *Uint64String                          `json:"createdBy,omitempty"`
	CreatedDate                  *time.Time                             `json:"createdDate,omitempty"`
	Direction                    *string                                `json:"direction,omitempty"`
	Id                           *Uint64String                          `json:"id,omitempty"`
	Identifier                   *string                                `json:"identifier,omitempty"`
	Metadata                     *[]Metadata                            `json:"metadata,omitempty"`
	Metrics                      *[]Metric                              `json:"metrics,omitempty"`
	Name                         *string                                `json:"name,omitempty"`
	Options                      *[]Metadata                            `json:"options,omitempty"`
	OrganizationId               *Uint64String                          `json:"organizationId,omitempty"`
	ProjectId                    *Uint64String                          `json:"projectId,omitempty"`
	Recordings                   *[]AssistantConversationRecording      `json:"recordings,omitempty"`
	Source                       *string                                `json:"source,omitempty"`
	Status                       *string                                `json:"status,omitempty"`
	TelephonyEvents              *[]AssistantConversationTelephonyEvent `json:"telephonyEvents,omitempty"`
	UpdatedBy                    *Uint64String                          `json:"updatedBy,omitempty"`
	UpdatedDate                  *time.Time                             `json:"updatedDate,omitempty"`
	User                         *User                                  `json:"user,omitempty"`
	UserId                       *Uint64String                          `json:"userId,omitempty"`
}

// AssistantConversationContext defines model for AssistantConversationContext.
type AssistantConversationContext struct {
	AssistantConversationId *Uint64String `json:"assistantConversationId,omitempty"`
	CreatedDate             *time.Time    `json:"createdDate,omitempty"`
	Id                      *Uint64String `json:"id,omitempty"`
	Key                     *string       `json:"key,omitempty"`
	UpdatedDate             *time.Time    `json:"updatedDate,omitempty"`
	Value                   *string       `json:"value,omitempty"`
}

// AssistantConversationMessage defines model for AssistantConversationMessage.
type AssistantConversationMessage struct {
	AssistantConversationId *Uint64String `json:"assistantConversationId,omitempty"`
	Content                 *string       `json:"content,omitempty"`
	CreatedDate             *time.Time    `json:"createdDate,omitempty"`
	Id                      *Uint64String `json:"id,omitempty"`
	Role                    *string       `json:"role,omitempty"`
	UpdatedDate             *time.Time    `json:"updatedDate,omitempty"`
}

// AssistantConversationRecording defines model for AssistantConversationRecording.
type AssistantConversationRecording struct {
	AssistantConversationId  *Uint64String `json:"assistantConversationId,omitempty"`
	AssistantRecordingUrl    *string       `json:"assistantRecordingUrl,omitempty"`
	ConversationRecordingUrl *string       `json:"conversationRecordingUrl,omitempty"`
	CreatedDate              *time.Time    `json:"createdDate,omitempty"`
	Id                       *Uint64String `json:"id,omitempty"`
	UpdatedDate              *time.Time    `json:"updatedDate,omitempty"`
	UserRecordingUrl         *string       `json:"userRecordingUrl,omitempty"`
}

// AssistantConversationTelephonyEvent defines model for AssistantConversationTelephonyEvent.
type AssistantConversationTelephonyEvent struct {
	AssistantConversationId *Uint64String           `json:"assistantConversationId,omitempty"`
	CreatedDate             *time.Time              `json:"createdDate,omitempty"`
	EventType               *string                 `json:"eventType,omitempty"`
	Id                      *Uint64String           `json:"id,omitempty"`
	Payload                 *map[string]interface{} `json:"payload,omitempty"`
	Provider                *string                 `json:"provider,omitempty"`
	UpdatedDate             *time.Time              `json:"updatedDate,omitempty"`
}

// AssistantDefinition defines model for AssistantDefinition.
type AssistantDefinition struct {
	AssistantId *Uint64String `json:"assistantId,omitempty"`
	Version     *string       `json:"version,omitempty"`
}

// Error defines model for Error.
type Error struct {
	ErrorCode    *Uint64String `json:"errorCode,omitempty"`
	ErrorMessage *string       `json:"errorMessage,omitempty"`
	HumanMessage *string       `json:"humanMessage,omitempty"`
}

// Metadata defines model for Metadata.
type Metadata struct {
	Id    *Uint64String `json:"id,omitempty"`
	Key   *string       `json:"key,omitempty"`
	Value *string       `json:"value,omitempty"`
}

// Metric defines model for Metric.
type Metric struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
	Value       *string `json:"value,omitempty"`
}

// Uint64String defines model for Uint64String.
type Uint64String = string

// User defines model for User.
type User struct {
	CreatedDate *time.Time    `json:"createdDate,omitempty"`
	Email       *string       `json:"email,omitempty"`
	Id          *Uint64String `json:"id,omitempty"`
	Name        *string       `json:"name,omitempty"`
	Role        *string       `json:"role,omitempty"`
	Status      *string       `json:"status,omitempty"`
}
