// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

// CreateBulkPhoneCallRequest defines model for CreateBulkPhoneCallRequest.
type CreateBulkPhoneCallRequest struct {
	PhoneCalls *[]CreatePhoneCallRequest `json:"phoneCalls,omitempty"`
}

// CreateBulkPhoneCallResponse defines model for CreateBulkPhoneCallResponse.
type CreateBulkPhoneCallResponse struct {
	Code    *int32                   `json:"code,omitempty"`
	Data    *[]AssistantConversation `json:"data,omitempty"`
	Error   *Error                   `json:"error,omitempty"`
	Success *bool                    `json:"success,omitempty"`
}

// CreatePhoneCallRequest defines model for CreatePhoneCallRequest.
type CreatePhoneCallRequest struct {
	Args       *map[string]interface{} `json:"args,omitempty"`
	Assistant  *AssistantDefinition    `json:"assistant,omitempty"`
	FromNumber *string                 `json:"fromNumber,omitempty"`
	Metadata   *map[string]interface{} `json:"metadata,omitempty"`
	Options    *map[string]interface{} `json:"options,omitempty"`
	ToNumber   *string                 `json:"toNumber,omitempty"`
}

// CreatePhoneCallResponse defines model for CreatePhoneCallResponse.
type CreatePhoneCallResponse struct {
	Code    *int32                 `json:"code,omitempty"`
	Data    *AssistantConversation `json:"data,omitempty"`
	Error   *Error                 `json:"error,omitempty"`
	Success *bool                  `json:"success,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    *int32 `json:"code,omitempty"`
	Error   *Error `json:"error,omitempty"`
	Success *bool  `json:"success,omitempty"`
}

// CreatePhoneCallJSONRequestBody defines body for CreatePhoneCall for application/json ContentType.
type CreatePhoneCallJSONRequestBody = CreatePhoneCallRequest

// CreateBulkPhoneCallJSONRequestBody defines body for CreateBulkPhoneCall for application/json ContentType.
type CreateBulkPhoneCallJSONRequestBody = CreateBulkPhoneCallRequest
