ALTER TABLE public.assistant_api_deployments ADD COLUMN greeting_interruptible boolean;
ALTER TABLE public.assistant_debugger_deployments ADD COLUMN greeting_interruptible boolean;
ALTER TABLE public.assistant_phone_deployments ADD COLUMN greeting_interruptible boolean;
ALTER TABLE public.assistant_web_plugin_deployments ADD COLUMN greeting_interruptible boolean;
ALTER TABLE public.assistant_whatsapp_deployments ADD COLUMN greeting_interruptible boolean;
